### ISSUE TITLE
Any plan on releasing a new version for django 1.10

### ISSUE THREAD

**Issue by ArnaudLevaufre** [geodesign/django-raster#14]
Hi,

It would be nice to have a new release that support django 1.10.

Thanks

**Comment by mflaxman10** [comment]
Hi Arnaud,

In concept I agree, and we will likely do so in short order.  Daniel is on well-deserved holidays, so it will be at least a few weeks.   If there are no unforeseen complications, then likely complete by early Sept. 

Mike Flaxman

**Comment by ArnaudLevaufre** [comment]
Ok thank you.

**Comment by yellowcap** [comment]
Just released Version 0.3 supporting Django 1.10

https://github.com/geodesign/django-raster/releases/tag/0.3
