### ISSUE TITLE
Crash when nodata_value == null

### ISSUE THREAD

**Issue by PaulWagener** [geodesign/django-raster#20]
https://github.com/geodesign/django-raster/blob/948864d97b789b0d12e505ed50816a0f76b92d2f/raster/algebra/parser.py#L245 crashes

numpy.ma.masked_values() crashes on the None that can be in the nodata_value.

**Comment by yellowcap** [comment]
Thanks for pointing this out, it is indeed a bug. I made a fix for it here:

https://github.com/geodesign/django-raster/commit/28b7f3af813f9278334be40264f3888476b5fea4

Will make a new release with this patch soon.

**Comment by PaulWagener** [comment]
Thanks for the quick fix!

**Comment by yellowcap** [comment]
You are welcome, it was easy to fix. Thanks for reporting!

**Comment by PaulWagener** [comment]
This line has the same issue: https://github.com/geodesign/django-raster/blob/master/raster/views.py#L230
