### ISSUE TITLE
Is there any example project or demo raster layer data for me to explore more?

### ISSUE THREAD

**Issue by twocucao** [geodesign/django-raster#23]
Is there any example project or demo raster layer data for me to explore more?

I'am opening an issue for **Django Raster**

My working env:

```bash
OS version : macos 10.12.5
Dependency: 
 - libgeotiff 1.4.2
 - gdal 1.11.5_2
Python version : 3.5
Package List: 
 - django 1.10.5
 - django-raster 0.5
```

I was stuck in creating a new raster layer (segmentation fault) when i submit a new raster tiff. And I search for a while and got nothing.

Can you give me a demo of raster layer of geotiff or tutorial so that i can try to explore more and produce the right things?

just ignore my poorly-written english.

I'm looking forward for your comments. Thanks

**Comment by yellowcap** [comment]
Maybe this is a data related issue. To check that, could you try to create a raster layer using the sample raster from the tests?

https://github.com/geodesign/django-raster/blob/master/tests/raster.tif.zip

This file is used during testing and should not give errors.

I don't have a full example project, but the tests section has a [barebones settings](https://github.com/geodesign/django-raster/tree/master/tests/testproj) for the test environment (using Celery).

**Comment by yellowcap** [comment]
@twocucao did you manage to solve the issue?

**Comment by yellowcap** [comment]
Not active anymore.
