### ISSUE TITLE
Using max() function in algebra

### ISSUE THREAD

**Issue by PaulWagener** [geodesign/django-raster#24]
Some functions require multiple arguments to be useful, such as max(), min(), sum() etc. But it seems the algebra parser is unable to handle formulas like `max(a,b)`. I get a 400 bad request on such formula's. Is there a different syntax I should be using?

**Comment by yellowcap** [comment]
The min/max are using the `numpy.amin` and `numpy.amax` functions, not the `numpy.minimum` and `numpy.maximum`. So min/max is an array aggregate not a array comparison. The formula parser does not support multiple arguments in a function at the moment. So allowing `min(a,b)` requires a deeper refactoring.

However, you can achieve the result you want with the following formula:

    a * (a > b) + b * (b > a)
