### ISSUE TITLE
SoftTimeLimitExceeded

### ISSUE THREAD

**Issue by bluespider42** [geodesign/django-raster#42]
On several rasters I get a SoftTimeLimitExceeded Error from celery, is this normal and do I need to change a setting somewhere? The files are tiffs ~30MB

**Comment by yellowcap** [comment]
This has to do with your celery configuration, not with django-raster. The parsing of larger raster files can take a while so you should increase your timeout limits.

https://docs.celeryproject.org/en/latest/userguide/configuration.html?highlight=CELERYD_TASK_SOFT_TIME_LIMIT#std:setting-task_soft_time_limit

**Comment by bluespider42** [comment]
Is there anyway to override this just for the raster tasks? all my other tasks should only take a few seconds. raster is the only one that should take much longer.
