### ISSUE TITLE
the problem about Raster Algebra

### ISSUE THREAD

**Issue by xxqhh** [geodesign/django-raster#43]
Hi,I have a problem about algebra.
![image](https://user-images.githubusercontent.com/20536019/65901904-b8472200-e3eb-11e9-9f50-6e5a079d67cf.png)

**Comment by xxqhh** [comment]
I found that the plus sign didn't seem to be parsed.
![image](https://user-images.githubusercontent.com/20536019/65904984-3d353a00-e3f2-11e9-93ad-62a4c6b2ccd6.png)

**Comment by yellowcap** [comment]
Yes you need to encode your formula parameter ("+" represents a white space in URLs, so you need to encode your url before requesting). Here is a tutorial on the topic https://www.urlencoder.io/python/
