### ISSUE TITLE
Raster fields require backends with raster support

### ISSUE THREAD

**Issue by vedmed85** [geodesign/django-raster#44]
Hi i faced with problem of installation and using(i installed all dependencies)
after executing 
python3 manage.py migrate
i receive error 
django.core.exceptions.ImproperlyConfigured: Raster fields require backends with raster support.

can somebody help me?

**Comment by yellowcap** [comment]
Django-raster only supports postgis as the DB backend. Are you using postgis?

**Comment by vedmed85** [comment]
Yes, i installed postgis before migrate

**Comment by yellowcap** [comment]
Please confirm that you have specified `'django.contrib.gis.db.backends.postgis'` as your db engine in the settings.

https://docs.djangoproject.com/en/2.2/ref/contrib/gis/tutorial/#configure-settings-py

**Comment by yellowcap** [comment]
Closed due to inactivity. Please re-open if still relevant.
