### ISSUE TITLE
Django 3 Compatibility

### ISSUE THREAD

**Issue by bluespider42** [geodesign/django-raster#46]
Package `six` has been removed from Django3

`  File "/usr/local/lib/python3.8/site-packages/raster/models.py", line 18, in <module>
    from raster.utils import hex_to_rgba
  File "/usr/local/lib/python3.8/site-packages/raster/utils.py", line 7, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (/usr/local/lib/python3.8/site-packages/django/utils/__init__.py)`

**Comment by yellowcap** [comment]
This was already addressed here https://github.com/geodesign/django-raster/commit/b257c7cb76ad28a9e4e3c7e985c310c55b35b0bb#diff-32b360aaa60a44ea075edecc114346b3 but I did not draft a release yet. I'll make a new release today.

**Comment by yellowcap** [comment]
This should be fixed now with latest release.
https://pypi.org/project/django-raster/0.8/
