### ISSUE TITLE
How to show DSM using 1 band raster?

### ISSUE THREAD

**Issue by orkunasa** [geodesign/django-raster#51]
Hello,

I'm trying to show digital surface model on Mapbox, but I couldn't apply the continuous colour scheme on the raster

The raster include only 1 band.

![Screenshot from 2020-08-06 01-43-22](https://user-images.githubusercontent.com/6940783/89471294-719e2300-d786-11ea-9dbc-eb14ccc1b677.png)

I tried below URL but didn't work very well. I see the colourized pixels but they are not related with elevation information.

`'http://127.0.0.1:8080/raster/algebra/{z}/{x}/{y}.png?layers=r:0=1&formula=r&scale=1964,6490&colormap={"continuous":true,"range":[0,255],"from":[165,0,38],"to":[0,104,55]}'`

Thank you

**Comment by yellowcap** [comment]
Hi Orkunasa, the range of the values in the metadata roughly 143 to 222. Maybe the range you applied is too large so you don't see the details of the data very well. Could you try to "narrow" the range to ``range=[143, 222]``?

This is not related to your problem, but as a comment, I think you could skip the "scale" parameter, its only used in RGB mode for 3 band rasters.

**Comment by orkunasa** [comment]
It works. Thank you @yellowcap
