### ISSUE TITLE
VARI formula parser error

### ISSUE THREAD

**Issue by orkunasa** [geodesign/django-raster#52]
Hello,

When I applied VARI formula on the tails, returns 400 bad request error. How can i solve this problem?
Min and max functions may solve this problem; however, they are not implemented right now.

VARI Formula:
**(Green - Red) / (Green + Red - Blue)**

My Tile URL:
http://127.0.0.1:8080/raster/algebra/{z}/{x}/{y}.png?layers=r:0=1,g:1=1,b:2=1&alpha&formula=(r-g)/(r+g-b)

Bands:

![Screenshot from 2020-08-21 16-10-53](https://user-images.githubusercontent.com/6940783/90895119-53f9cc00-e3ca-11ea-9870-64f3c73b5de9.png)

Thank you.

**Comment by yellowcap** [comment]
I don't think that the VARI index is always between -1 and 1. If in your formula red = 100, green = 0, and blue = 50, the result is 2 right?

On a side note, the reference I found for this index used (green- red), your formula is (red - green).

https://www.harrisgeospatial.com/docs/BroadbandGreenness.html#Visible

**Comment by orkunasa** [comment]
You're right!
Thank you for your help.
