### ISSUE TITLE
ModuleNotFoundError: No module named 'celery.task'

### ISSUE THREAD

**Issue by morysam96** [geodesign/django-raster#54]
hi
i get error After I adjust:
1-pip install django-raster
2-INSTALLED_APPS = (
...
'raster',
)
3-path('raster/', include('raster.urls')),
4-python manage.py migrate

version my python 38 -64bit
get error after add layer:
ModuleNotFoundError: No module named 'celery.task'
 "POST /admin/raster/rasterlayer/add/ HTTP/1.1" 500 164659

**Comment by tobiasmllr** [comment]
I had the same problem. The '@task' decorator is deprecated since celery5.
I replaced '@task' with '@shared_task' in .../lib/python3.8/site-packages/raster/tasks.py of my python environment. Also replace:
from celery import group, shared_task
